name: Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: pnpm/action-setup@master
        with:
          version: latest
      - uses: DimensionDev/github-token-action@latest
        with:
          registry: true
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - name: Publish to GitHub Package (unstable)
        run: ./scripts/publish-to-github.sh
